'''
Soundtrap-related tools and utilities

'''



import collections

from typing import Iterable

SoundtrapSample = collections.namedtuple('SoundtrapSample', ['start_time', 'end_time', 'min_frequency', 'max_frequency', 'description'])
''' Representation of data generated by SoundTrap '''

def soundtraps_data_convention (data_iterable : Iterable) -> SoundtrapSample:
    if isinstance (data_iterable, list):
        return SoundtrapSample(
            start_time= float(data_iterable[0]),
            end_time= float(data_iterable[1]),
            min_frequency= float(data_iterable[2]),
            max_frequency= float(data_iterable[3]),
            description= data_iterable[4]
        )


